# Generated by Django 5.2.6 on 2025-09-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_testingdatabase_delete_enrollment_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('brgy', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('postal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('prof', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('ave_grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stud_fam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('annueal_inc', models.CharField(max_length=100)),
                ('citizenship', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('student_id', models.IntegerField()),
                ('ave_grade', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TestingDatabase',
        ),
    ]
