# Generated by Django 5.2.5 on 2025-10-06 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_account_address_school_stud_fam_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud_fam',
            old_name='annueal_inc',
            new_name='annual_inc',
        ),
    ]
